Use dockerdb;

DROP TABLE IF EXISTS posts;

CREATE TABLE posts
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    title NVARCHAR(100) NOT NULL,
    content NVARCHAR(140) NOT NULL,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);